name: Build APK

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.keystore

      - name: Add signing configs to gradle.properties
        run: |
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> ./app/gradle.properties
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> ./app/gradle.properties
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> ./app/gradle.properties

      - name: Build signed release APK
        run: ./gradlew :app:assembleRelease --build-cache --no-daemon

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: away-text-release-apk
          path: app/build/outputs/apk/release/*.apk
